### ISSUE TITLE
Nova:tool babel and laravel-mix issue

### ISSUE THREAD

**Issue by elijahworkz** [laravel/nova-issues#1463]
When I created new tool (php artisan nova:tool ) - in installation process when compiling the assets I got this error:

```
ERROR in ./resources/js/tool.js
Module build failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/home/ilya/projects/sites/eTeacher/lpm/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/home/ilya/projects/sites/eTeacher/lpm/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at api (/home/ilya/projects/sites/eTeacher/lpm/node_modules/@babel/plugin-syntax-dynamic-import/lib/index.js:19:7)
    at /home/ilya/projects/sites/eTeacher/lpm/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/home/ilya/projects/sites/eTeacher/lpm/nova-components/PageEditor/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/home/ilya/projects/sites/eTeacher/lpm/nova-components/PageEditor/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /home/ilya/projects/sites/eTeacher/lpm/nova-components/PageEditor/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/home/ilya/projects/sites/eTeacher/lpm/nova-components/PageEditor/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/ilya/projects/sites/eTeacher/lpm/nova-components/PageEditor/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/home/ilya/projects/sites/eTeacher/lpm/nova-components/PageEditor/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/ilya/projects/sites/eTeacher/lpm/nova-components/PageEditor/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/ilya/projects/sites/eTeacher/lpm/nova-components/PageEditor/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/ilya/projects/sites/eTeacher/lpm/nova-components/PageEditor/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/ilya/projects/sites/eTeacher/lpm/nova-components/PageEditor/node_modules/babel-loader/lib/index.js:50:20)
    at /home/ilya/projects/sites/eTeacher/lpm/nova-components/PageEditor/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/home/ilya/projects/sites/eTeacher/lpm/nova-components/PageEditor/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
 @ multi ./resources/js/tool.js ./resources/sass/tool.scss
```

I have traced it to laravel-mix module which loads the old babel-core. I decided to update laravel-mix and got some vulnearabilities warnings

```
=== npm audit security report ===                        
                                                                                
# Run  npm install --save-dev laravel-mix@4.0.15  to resolve 2 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ braces                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ laravel-mix [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ laravel-mix > webpack-dev-server > http-proxy-middleware >   │
│               │ micromatch > braces                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/786                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Missing Origin Validation                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ webpack-dev-server                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ laravel-mix [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ laravel-mix > webpack-dev-server                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/725                             │
└───────────────┴──────────────────────────────────────────────────────────────┘

```
after updating the laravel-mix to 4.0.15 I was able to compile with no errors but the tool itself is not visible on the page.
I'm using Nova 1.3.2 on Laravel 5.7

I have tried different variations of just installing a babel bridge instead of updating laravel-mix, but then I get a different error:

```
ERROR in ./resources/js/tool.js
Module build failed: TypeError: this.setDynamic is not a function
    at PluginPass.pre (/home/ilya/projects/sites/eTeacher/lpm/nova-components/PageEditor/node_modules/babel-plugin-transform-runtime/lib/index.js:31:12)
    at transformFile (/home/ilya/projects/sites/eTeacher/lpm/node_modules/@babel/core/lib/transformation/index.js:78:27)
    at runSync (/home/ilya/projects/sites/eTeacher/lpm/node_modules/@babel/core/lib/transformation/index.js:45:3)
    at transformSync (/home/ilya/projects/sites/eTeacher/lpm/node_modules/@babel/core/lib/transform.js:43:38)
    at Object.transform (/home/ilya/projects/sites/eTeacher/lpm/node_modules/@babel/core/lib/transform.js:22:38)
    at transpile (/home/ilya/projects/sites/eTeacher/lpm/nova-components/PageEditor/node_modules/babel-loader/lib/index.js:50:20)
    at /home/ilya/projects/sites/eTeacher/lpm/nova-components/PageEditor/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/home/ilya/projects/sites/eTeacher/lpm/nova-components/PageEditor/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
 @ multi ./resources/js/tool.js ./resources/sass/tool.scss
```

**Comment by davidhemphill** [comment]
Sorry, but there's not enough details to replicate this. Feel free to chime in with any more informaiton.

**Comment by elijahworkz** [comment]
> Sorry, but there's not enough details to replicate this. Feel free to chime in with any more informaiton.

what sort of information do you need?

**Comment by elijahworkz** [comment]
in my laravel install i have these babel dependencies:
"@babel/plugin-syntax-dynamic-import": "^7.2.0",
"@babel/preset-env": "^7.3.4",

here's my babelrc settings:
```
{
	"presets": [
		"@babel/preset-env"
	],
	"plugins": [
		"@babel/plugin-syntax-dynamic-import"
	]
}
```

**Comment by davidhemphill** [comment]
Your Laravel project dependencies do not matter in this case. Are you using the one provided from the `artisan nova:tool` generator?

**Comment by elijahworkz** [comment]
@davidhemphill  yes - I just ran the generator and that's when first error happened.
I have created tools on this install some time ago (several nova updated ago) and they work but as soon as I ran npm run dev to compile them - I started to get the same error about babel

**Comment by elijahworkz** [comment]
@davidhemphill 
I have fixed it but I still don't know what exactly the problem was - if it was just me or if nova:tool is not compatible with babel 7 in general.

Here's what I did. 
I installed fresh laravel 5.7, installed nova 1.3.2 and installed a new tool
- everything worked fine

I copied the folder with this working tool to my current laravel install and I was able to see the tool without any problems (before it didn't show anything)
I then tried to run npm run dev on the tool to compile the changes and started to get same babel 7.0.0. error

I have removed all babel dev dependencies that I had in my laravel package.json and removed .babelrc
Error went away and I was able to compile and see the change on the frontend.

**Comment by rikless** [comment]
@davidhemphill since L5.7, laravel mix is the latest version, whitch uses webpack 4.

This is why the build failed. In my case, when I generate a tool, I need to update multiple files to void this error.

Maybe a good time to consider https://github.com/laravel/nova/pull/244

**Comment by aihowes** [comment]
I've had the same issue but when creating a field using the CLI generator.

I believe this issue occurs if you have a `.babelrc` file in your project root that references any new babel plugins e.t.c.

Using any laravel-mix build commands will look for `.babelrc` which seems to be then find it at the project root, if your `.babelrc` file contains any babel 7 plugins it errors out as mix 1.7.2 uses babel 6 (babel-core).

@elijahworkz does your project have a `.babelrc` file?

**Comment by elijahworkz** [comment]
I do. It's been a long time now and I don't remember what I did, but from
the looks of  package.json - I removed the new babel packages and went with
6.*
(I have babel-plugin-syntax-dynamic-import)

Elijahworkz STUDiO

**Comment by robinstraub** [comment]
Posting here as I stumbled on this issue.

A .babelrc in the project root will be parsed by laravel-mix in the tool sub directory. What caused the issue for me is having a plugin which requires babel 7

/.babelrc
```
{
    "plugins": ["@babel/plugin-syntax-dynamic-import"]
}
```

I added the following .babelrc in the tool root directory to reset the plugins, this fixed the issue.

/nova-components/CustomTool/.babelrc
```
{
    "plugins": []
}
```

This lets you use babel 7 in your main project and babel 6 for nova tools.

**Comment by elijahworkz** [comment]
@robinstraub  thanks! I will try that

**Comment by XternalSoft** [comment]
@robinstraub You're awesome !

**Comment by h-zone** [comment]
conflict solves by adding `.babelrc` in nova-components directory with follow content
```json
{
}
```
thus, it interrupts the babel settings in the directory above

**Comment by infostreams** [comment]
The above works! Thanks. I would recommend a .babelrc with the following content though

```json
{
    "ignore": "this file is here because of https://github.com/laravel/nova-issues/issues/1463#issuecomment-502436507"
}
```

so that it is clear why this weird file is even in your repository in the first place

**Comment by rgdigital** [comment]
> /nova-components/CustomTool/.babelrc
> 
> ```
> {
>     "plugins": []
> }
> ```

Worked for me, thanks!

**Comment by nokulf** [comment]
> /nova-components/CustomTool/.babelrc
> 
> ```
> 
>     "plugins": []
> }
> ```

Worked, thanks!
