### ISSUE TITLE
Value metrics still broken when suffix is used

### ISSUE THREAD

**Issue by ChrisHardie** [laravel/nova-issues#3359]
- Laravel Version: 8.38.0
- Nova Version: 3.23.2
- PHP Version: 7.4.16
- Database Driver & Version: mysql 8.0.22
- Operating System and Version: Vapor and also Valet on MacOS 11.2.3 
- Browser type and version: Various including Safari 14.0.3

### Description:

Following up on #3263, it looks like a fix was made for Partition metrics, but at least for me, Value metrics are still affected by this bug.

### Detailed steps to reproduce the issue on a fresh Nova installation:

If I use a calculate function where the calculated value is, for example, ` 1280.6100065567`, the metric can only be displayed if there is no call to `suffix()`. If I include that call, I get the same "TypeError: t.match is not a function" console error and ever-processing metric card visual as in the previous bug report.

```
    public function calculate(NovaRequest $request)
    {
        return $this->result(
            Carbon::parse(
                TrackingObject::active()
                    ->where('admin_pause_checks', false)
                    ->where('source_pause_checks', false)
                    ->min('last_checked')
            )->floatDiffInHours()
        )
            ->format('0.0')
            ->suffix('hour');
    }
```

![Screen Shot 2021-04-21 at 13 32 45](https://user-images.githubusercontent.com/311772/115596436-19706800-a2a6-11eb-9dc1-d640ce323b6e.png)

If I remove the call to `suffix()`, I get something more usable:

![Screen Shot 2021-04-21 at 13 36 47](https://user-images.githubusercontent.com/311772/115596945-b206e800-a2a6-11eb-9d28-95b3ab9abbdc.png)

**Comment by wilng2005** [comment]
Have encountered this bug as well, definitely needs fixing.

As a temporary workaround, i added an additional call to withoutSuffixInflection() for the component to at least display something useful. Example below.

```  
    public function calculate(NovaRequest $request)
    {
        return $this->result(
            Carbon::parse(
                TrackingObject::active()
                    ->where('admin_pause_checks', false)
                    ->where('source_pause_checks', false)
                    ->min('last_checked')
            )->floatDiffInHours()
        )
            ->format('0.0')
            ->suffix('hour(s)')
            ->withoutSuffixInflection();
    }
```

**Comment by crynobone** [comment]
Fixed in [v3.24.0 release](https://nova.laravel.com/releases/3.24.0).

**Comment by ChrisHardie** [comment]
@crynobone Unfortunately I'm still seeing an error after updating to 3.24.0:

`TypeError: t.match is not a function. (In 't.match(/^(.*)[A-Za-zÀ-ÖØ-öø-ÿ]$/)', 't.match' is undefined)`

I made sure to run `php artisan nova:publish` and rebundle the JS. Is there something else I should try?

**Comment by crynobone** [comment]
Seem like `laravel/nova-js` v1.11.1 doesn't contain the correct changes.

**Comment by crynobone** [comment]
This has been fixed with [v3.25.0 release](https://nova.laravel.com/releases/3.25.0).

Also please use `laravel-nova` v1.12.3 or above if you're using it from npm.

**Comment by milewski** [comment]
I get server error 500 when trying to download the latest version from: https://nova.laravel.com/releases

![image](https://user-images.githubusercontent.com/2874967/117921783-ea3c9c00-b323-11eb-918e-8176672e0e35.png)

**Comment by crynobone** [comment]
@milewski can you try again. I do manage to download from the site using my personal account.

**Comment by milewski** [comment]
Thanks, it worked now.
